config/routes.rb
Sobre::Application.routes.draw do
  devise_for :users do
    root :to => 'devise/registrations#new'
  end

  resources :dashboard, :only => :index do
    collection do
      get :success
    end
  end
  resources :users, :only => :show
  resources :pages, :only => [:show, :update]

  get '/get_started' => "public_pages#get_started", :as => 'get_started'
  get '/contact' => "public_pages#contact", :as => 'contact'
  post '/dispatch_email' => "public_pages#dispatch_email", :as => 'dispatch_email'

  match '/:username' => 'users#show', :as => 'users_show'
end

app/models/page.rb
class Page
  include Mongoid::Document

  field :title,       :type => String
  field :subtitle,    :type => String
  field :description, :type => String, :default => ''
  field :twitter,     :type => String
  field :facebook,    :type => String
  field :linkedin,    :type => String
  field :orkut,       :type => String
  field :address,     :type => String
  field :phone,       :type => String
  field :email,       :type => String
  field :theme,       :type => String, :default => '01'

  embedded_in :user
end

app/models/user.rb
class User
  include Mongoid::Document

  field :username, :type => String
  field :name, :type => String

  embeds_one :page

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me, :username, :name

  validates_presence_of :username
  validates_uniqueness_of :username, :case_sensitive => false
  validates_format_of :username, :with => /^[a-zA-Z0-9_]*$/i

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  after_create :create_page
  after_create :send_welcome_email

  def theme
    "theme-" + page.theme
  end

  private

  def send_welcome_email
    ContactMailer.welcome_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    dashboard_index_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
  before_filter :authenticate_user!
  actions :update

  def update
    update! do |format|
      format.html { redirect_to success_dashboard_index_path }
    end
  end

  private

  def resource
    current_user.page
  end
end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController
  layout 'registrations'
  respond_to :js

  def dispatch_email
    if validate_params! and ContactMailer.contact_email(params[:contact]).deliver
      flash[:notice] = "Mensagem enviada."
    else
      flash[:notice] = "Oops. Houve algum problema ao enviar a mensagem"
    end
  end

  private

  def validate_params!
    params[:contact][:email].present? and params[:contact][:name].present? and params[:contact][:message].present?
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  actions :show

  def show
    show! do |format|
      format.html { render :layout => 'registrations' unless resource }
    end
  end

  private

  def resource
    @user = User.where(:username => /^#{params[:username]}$/i).first
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'registrations'
  respond_to :js

  def dispatch_email
    if validate_params! and ContactMailer.contact_email(params[:contact]).deliver
      flash[:notice] = "Mensagem enviada."
    else
      flash[:notice] = "Oops. Houve algum problema ao enviar a mensagem"
    end
  end

  private

  def validate_params!
    params[:contact][:email].present? and params[:contact][:name].present? and params[:contact][:message].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def selected_class(path)
    current_page?(path) ? "selected" : ""
  end

  def theme_class
    current_page?(dashboard_index_path) ? current_user.theme : @user.theme
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
  def social_network_to(network, username)
    link_to network.to_s, social_network_url(network, username), :class => network.to_s, :target => :blank, :style => username.blank? ? 'display:none' : ''
  end

  def social_network_url(network, username)
    case network
    when :twitter
      'http://twitter.com/' + username
    when :facebook
      'http://facebook.com/' + username
    when :linkedin
      'http://linkedin.com/in/' + username
    when :orkut
      'http://orkut.com/' + username
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def social_network_to(network, username)
    link_to network.to_s, social_network_url(network, username), :class => network.to_s, :target => :blank, :style => username.blank? ? 'display:none' : ''
  end

  def social_network_url(network, username)
    username ||= ''

    case network
    when :twitter
      'http://twitter.com/' + username
    when :facebook
      'http://facebook.com/' + username
    when :linkedin
      'http://linkedin.com/in/' + username
    when :orkut
      'http://orkut.com/' + username
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_field.html.haml
- type ||= :text_field
.editable-box{:class => field.to_s + "-input"}
  %span.seta
  %label Editar:
  = f.send(type, field)
  %button.shiny-blue{:disabled => :disabled} OK

app/views/dashboard/_information_form.html.haml
#information-form{:style => 'display:none'}
  %p.save{:style => 'display:none'} Salvando...
  = link_to "fechar", "#", :class => 'close-form'
  = form_for current_user.information, :method => :put do |f|
    %p
      = f.label :title
      = f.text_field :title
    %p
      = f.label :subtitle
      = f.text_field :subtitle
    %p
      = f.label :description
      = f.text_field :description
    %p
      = f.label :twitter
      = f.text_field :twitter
    %p
      = f.label :facebook
      = f.text_field :facebook
    %p
      = f.label :linkedin
      = f.text_field :linkedin
    %p
      = f.label :orkut
      = f.text_field :orkut
    %p
      = f.label :address
      = f.text_field :address
    %p
      = f.label :phone
      = f.phone_field :phone
    %p
      = f.label :email
      = f.email_field :email

app/views/dashboard/_page_form.html.haml
#page-form
  = form_for current_user.page, :method => :put do |f|
    -#%p
      - %w( 01 02 03 ).each do |theme|
        = f.radio_button :theme, theme, :class => 'theme'
        = f.label "theme_#{theme}", theme
        %br

app/views/dashboard/_user_page.html.haml
= form_for current_user.page, :method => :put do |f|
  %header.titulo
    .align-center
      %h2.title.editable-hover.tooltip{ :title => "Clique para editar" }= resource.page.title
      = render 'field', :field => :title, :f => f

  %header.sub-titulo
    .align-center
      %h3.subtitle.editable-hover.tooltip{ :title => "Clique para editar" }= resource.page.subtitle
      = render 'field', :field => :subtitle, :f => f

  %section.content
    %article
      .align-center
        %p.description.editable-hover.tooltip{ :title => "Clique para editar" }= resource.page.description.gsub("\n", "<br />").html_safe
        = render 'field', :field => :description, :f => f, :type => :text_area

    %aside.network
      .align-center
        %section.network
          = link_to 'linkedin', 'javascript:void(0);', :class => 'linkedin editable-hover tooltip', :title => "Clique para editar"
          = render 'field', :field => :linkedin, :f => f
          = link_to 'orkut', 'javascript:void(0);', :class => 'orkut editable-hover tooltip', :title => "Clique para editar"
          = render 'field', :field => :orkut, :f => f
          = link_to 'facebook', 'javascript:void(0);', :class => 'facebook editable-hover tooltip', :title => "Clique para editar"
          = render 'field', :field => :facebook, :f => f
          = link_to 'twitter', 'javascript:void(0);', :class => 'twitter editable-hover tooltip', :title => "Clique para editar"
          = render 'field', :field => :twitter, :f => f

    %aside.address-content
      .align-center
        %section.address-content
          %p
            %span.e-mail
              Email:
            %span.email-client.editable-hover.tooltip{ :title => "Clique para editar" }
              = link_to((resource.page.email || ''), "javascript:void(0)", :class => 'email')
            = render 'field', :field => :email, :f => f
          %p
            %span.telephone
              Telefone:
            %span.email-client.phone.editable-hover.tooltip{ :title => "Clique para editar" }
              = resource.page.phone
            = render 'field', :field => :phone, :f => f
          %address
            %span.endereco
              Endereço:
            %span.endereco-client.address.editable-hover.tooltip{ :title => "Clique para editar" }
              = resource.page.address
            = render 'field', :field => :address, :f => f

  %button.shiny-blue Publicar

app/views/dashboard/index.html.haml
.client-layout{:class => theme_class}
  = render 'user_page', :resource => current_user

- content_for :footer do
  = javascript_include_tag 'dashboard'

app/views/dashboard/success.html.haml
.align-center
  yo! be happy!

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "pt-br"}
  %head
    %meta{:charset => "UTF-8"}
    = stylesheet_link_tag 'themes'
    %title= yield :title

  %body
    .all-content
      = yield

    %footer
      .align-center
        %p Sob.re | Todos os direitos reservados
      = render 'shared/google_analytics.html.erb'
      = yield :footer

app/views/layouts/dashboard.html.haml
!!! 5
%html{:lang => "pt-br"}
  %head
    %meta{:charset => "UTF-8"}
    = stylesheet_link_tag "themes"
    = stylesheet_link_tag "dashboard"
    %title= "Sob.re - Dashboard de #{current_user.identifier}"

  %body
    .all-content
      // .choose-template Template
      .header-sobre
        .align-center
          = link_to image_tag("logo-dashboard.png"), "javascript:void(0);"
          .user-details
            = link_to 'Editar perfil', edit_user_registration_path
            |
            = link_to 'Sair', destroy_user_session_path, :method => :delete
          .user-page
            = link_to content_tag(:span, "http://sob.re/") + current_user.username, users_show_url(current_user.username)

      .align-center
        %p.personalize
          Personalize sua página
          %span
            Selecione um template e adicione as informações

      .user-page-box
        .align-user-page
          = yield

      %footer
        .align-center
          %p Sob.re | Todos os direitos reservados
        = render 'shared/google_analytics.html.erb'
        = yield :footer

app/views/layouts/registrations.html.haml
!!! 5
%html{:lang => "pt-br"}
  %head
    %meta{:charset => "UTF-8"}
    %meta{:name => "robots", :content => "index, follow"}
    %meta{:name => "keywords", :content => "site fácil, site pronto, site sem conhecimento técnico"}
    %meta{:name => "description", :content => "Criação de sites sem necessidade técnica, com apenas um único passo e um formulário simples, você coloca sua empresa na internet sem dor de cabeça."}

    = stylesheet_link_tag 'application'
    %title Sob.re sua empresa facilmente na internet

  %body
    .all-content
      %section.faixa
        .align-center
          = link_to "Já é um usuário?", "#", :class => 'login-link' unless current_user

      %section.login
        .align-center
          = render 'shared/login'

      %header
        .align-center
          = link_to image_tag("logo.png"), "/", :class => "logo"
          = render :partial => "shared/menu"
      .content
        .align-center
          = yield

      %footer
        .align-center
          %p Sob.re | Todos os direitos reservados
        = javascript_include_tag 'application'
        = render 'shared/google_analytics.html.erb'

app/views/public_pages/contact.html.haml
.contact-page
  %h4 Entre em contato
  .flashes
  = form_tag dispatch_email_path, :method => :post, :remote => true do
    = label_tag 'contact_name', 'Nome'
    = text_field_tag 'contact[name]', nil, :placeholder => "Seu Nome", :class => "required"

    = label_tag 'contact_email', 'Email'
    = text_field_tag 'contact[email]', nil, :placeholder => 'E-mail', :class => "required"

    = label_tag 'contact_message', 'Mensagem'
    = text_area_tag 'contact[message]', nil, :placeholder => 'Sua Mensagem', :class => "required"

    %button{:class => "shiny-blue"}
      Enviar

app/views/public_pages/dispatch_email.js.erb
$('.flashes').html("<%= flash[:notice] %>");

app/views/public_pages/get_started.html.haml
.image-box
  = image_tag "layouts.png"

.box-text
  %p.text-description
    Sob.re é um sistema de <b>criação rápida de páginas web.</b><br />
    A partir de templates pré-definidos é possível criar uma página<br />
    para sua empresa ou publicar suas informações de contato,<br />
    preenchendo apenas um <b>curto formulário.</b><br />
    <br />
    O Sob.re é <b>simples, rápido e fácil de utilizar.</b> Feito para você<br />
    que não pode investir em um webdesigner profissional ou que<br />
    precisa o quanto antes de uma página na internet.<br />

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18974991-5']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_google_analytics.html.haml
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18974991-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_login.html.haml
#login-box{:style => "display:none"}
  = form_for(:user, :url => session_path(:user)) do |f|
    = f.label :email, :class => 'hide'
    = f.email_field :email, :placeholder => "EMAIL"

    = f.label :password, :class => 'hide'
    = f.password_field :password, :placeholder => "SENHA"

    = f.check_box :remember_me
    = f.label :remember_me, "Mantenha-me conectado"

    %button{:class => "shiny-blue"}
      Entrar

app/views/shared/_menu.html.haml
%ul.menu
  %li{:class => selected_class('/')}
    %span.seta
    %span
      = link_to "Home", "/"

  %li{:class => selected_class('/blog')}
    %span.seta
    %span
      = link_to "Blog", "#"

  %li{:class => selected_class(get_started_path)}
    %span.seta
    %span
      = link_to "Conheça", get_started_path

  %li{:class => selected_class(contact_path)}
    %span.seta
    %span
      = link_to "Contato", contact_path, :class => "last"

app/views/users/_user_page.html.haml
%div{:class => theme_class}
  %header.titulo
    .align-center
      %h2.title= resource.page.title

  %header.sub-titulo
    .align-center
      %h3.subtitle= resource.page.subtitle

  %section.content
    %article
      .align-center
        %p.description= resource.page.description.gsub("\n", "<br />").html_safe

    %aside.network
      .align-center
        %section.network
          = social_network_to(:linkedin, resource.page.linkedin)
          = social_network_to(:orkut, resource.page.orkut)
          = social_network_to(:facebook, resource.page.facebook)
          = social_network_to(:twitter, resource.page.twitter)

    %aside.address-content
      .align-center
        %section.address-content
          %p.email-layer{:style => resource.page.email.blank? ? 'display:none' : ''}
            %span.e-mail
              Email:
            %span.email-client
              = mail_to(resource.page.email, nil, :class => 'email')
          %p.phone-layer{:style => resource.page.phone.blank? ? 'display:none' : ''}
            %span.telephone
              Telefone:
            %span.email-client.phone
              = resource.page.phone
          %address.address-layer{:style => resource.page.address.blank? ? 'display:none' : ''}
            %span.endereco
              Endereço:
            %span.endereco-client.address
              = resource.page.address

- content_for :title do
  = "Sob.re - #{resource.page.title}"

app/views/users/show.html.haml
- if resource
  = render 'user_page'

- else
  %p Not found